"""Pack tools/glyphs.py into the compact table the device imports.

Layout per glyph:  advance, nshapes, then per shape either

    0, x0, y0, x1, y1      axis-aligned rectangle
    n, x0, y0, ... xn, yn  filled polygon with n >= 3 points

Rectangles get their own opcode because PicoGraphics fills them roughly
four times faster than the equivalent polygon, and most strokes in this
face are axis-aligned.

All coordinates fit in a byte (0..33 on the 20x28 authoring grid).
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import glyphs

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "device", "font_data.py")


def as_rect(poly):
    """Return (x0, y0, x1, y1) if poly is an axis-aligned rectangle."""
    if len(poly) != 4:
        return None
    xs = sorted({int(round(p[0])) for p in poly})
    ys = sorted({int(round(p[1])) for p in poly})
    if len(xs) != 2 or len(ys) != 2:
        return None
    corners = {(int(round(x)), int(round(y))) for x, y in poly}
    if corners != {(xs[0], ys[0]), (xs[1], ys[0]),
                   (xs[1], ys[1]), (xs[0], ys[1])}:
        return None
    return xs[0], ys[0], xs[1], ys[1]


def pack(ch):
    w, polys = glyphs.GLYPHS[ch]
    out = bytearray([glyphs.advance(ch), len(polys)])
    rects = 0
    for poly in polys:
        r = as_rect(poly)
        if r:
            rects += 1
            out.append(0)
            out += bytes(r)
            continue
        out.append(len(poly))
        for x, y in poly:
            xi, yi = int(round(x)), int(round(y))
            assert 0 <= xi < 256 and 0 <= yi < 256, (ch, x, y)
            out += bytes((xi, yi))
    return bytes(out), rects, len(polys)


def main():
    lines = [
        '"""Generated by tools/build_font.py — do not edit by hand."""',
        "",
        "CAP = %d" % glyphs.CAP,
        "STEM = %d" % glyphs.STEM,
        "",
        "G = {",
    ]
    total = rect_n = shape_n = 0
    for ch in sorted(glyphs.GLYPHS):
        data, rects, shapes = pack(ch)
        total += len(data)
        rect_n += rects
        shape_n += shapes
        lines.append("    %r: %r," % (ch, data))
    lines.append("}")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote %s" % os.path.normpath(OUT))
    print("  %d glyphs, %d bytes, %d/%d shapes are fast rectangles (%d%%)"
          % (len(glyphs.GLYPHS), total, rect_n, shape_n,
             100 * rect_n // max(1, shape_n)))


if __name__ == "__main__":
    main()
